pages:
  image: python:3.9-slim
  before_script:
  # install Git for the mkdocs revision plugin
  - time apt update && apt-get install -y git
  # Install mkdocs and theme
  - time pip install -r requirements.txt
  stage: deploy
  tags:
    - hva
  variables:
    ENABLED_GIT_REVISION_DATE: "true"
    GIT_DEPTH: 1000
  script:
  - time mkdocs build --site-dir public
  - time cp -rf game public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - deploy

deploy_to_itch:
  image: python:3.9-slim
  stage: deploy
  before_script:
    - apt update && apt install -y git wget unzip
    - wget -q https://broth.itch.ovh/butler/linux-amd64/head/archive/default -O butler.zip
    - unzip butler.zip -d /usr/local/bin/
    - chmod +x /usr/local/bin/butler
  script:
    - butler push game "$itch_user/$itch_project_name:windows" --if-changed
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $CI_COMMIT_TAG'
  tags:
    - hva